var http = require("http")
var urls = [
	"http://www.perriconemd.com/skincare/moisturizers/hyalo-plasma-MP0033.html",
	"http://www.perriconemd.com/gift-ideas/gifts-for-you/fabulous-eyes-in-a-flash-90376.html",
	"http://www.perriconemd.com/skincare/treatments/ovm-serum-MP0092.html",
	"http://www.perriconemd.com/sets/perfect-pairs/beauty-from-the-inside-out-91080.html",
	"http://www.perriconemd.com/skincare/treatments/vitamin-c-ester-serum-MP0080.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-bronzer-bronzer-MP0056.html",
	"http://www.perriconemd.com/skincare/treatments/neuropeptide-facial-conformer-super-size-MP0050.html",
	"http://www.perriconemd.com/skincare/cleansers/neuropeptide-facial-cleanser-MP0045.html",
	"http://www.perriconemd.com/skincare/neck-body/neuropeptide-necolletage-anti-aging-neck-cream-MP0094.html",
	"http://www.perriconemd.com/skincare/neck-body-firming/neuropeptide-necolletage-super-size-MP0054.html",
	"http://www.perriconemd.com/skincare/treatments/neuropeptide-facial-conformer-MP0091.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/acyl-glutathione-eye-lid-serum-MP0004.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-blush-blush-MP0055.html",
	"http://www.perriconemd.com/skincare/shop-by-prescription/brighten-and-protect/vitamin-c-ester-eye-serum-MP0082.html",
	"http://www.perriconemd.com/skincare/treatments/ovm-MP0067.html",
	"http://www.perriconemd.com/skincare/treatments/dmae-firming-pads-MP0083.html",
	"http://www.perriconemd.com/supplements/skin-health/omega-3-supplements-MP0066.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-foundation-foundation-no.-2-MP0058.html",
	"http://www.perriconemd.com/supplements/skin-health/skin-clear-supplements-MP0076.html",
	"http://www.perriconemd.com/skincare/cleansers/nutritive-cleanser-MP0065.html",
	"http://www.perriconemd.com/skincare/moisturizers/face-finishing-moisturizer-super-size-MP0090.html",
	"http://www.perriconemd.com/skincare/treatments/blue-plasma-peel-MP0008.html",
	"http://www.perriconemd.com/skincare/exfoliators-toners/firming-facial-toner-MP0023.html",
	"http://www.perriconemd.com/skincare/shop-by-product/new/refirm-MP0087.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/refirm-eye-MP0095.html",
	"http://www.perriconemd.com/skincare/treatments/anti-wrinkle-acyl-glutathione-MP0002.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-highligher-highlighter-MP0061.html",
	"http://www.perriconemd.com/skincare/treatments/high-potency-evening-aging-repair-MP0030.html",
	"http://www.perriconemd.com/sets/travel-size-skincare/the-science-of-plasma-7262.html",
	"http://www.perriconemd.com/gift-ideas/gifts-for-him/the-crease-cure-duo-7117.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/advanced-eye-area-therapy-MP0005.html",
	"http://www.perriconemd.com/sets/limited-edition/the-cold-plasma-collection-91000.html",
	"http://www.perriconemd.com/supplements/skin-health/skin-total-body-anti-aging-supplements-MP0075.html",
	"http://www.perriconemd.com/best-skin-care-products/super-berry-with-acai-MP0077.html",
	"http://www.perriconemd.com/skincare/exfoliators-toners/neuropeptide-face-activator-MP0049.html",
	"http://www.perriconemd.com/gift-ideas/gifts-for-him/blue-plasma-cleansing-treatment-MP0009.html",
	"http://www.perriconemd.com/skincare/moisturizers/photo-plasma-MP0071.html",
	"http://www.perriconemd.com/skincare/moisturizers/face-finishing-moisturizer-MP0021.html",
	"http://www.perriconemd.com/skincare/moisturizers/face-finishing-moisturizer-tint-MP0022.html",
	"http://www.perriconemd.com/sets/limited-edition/the-vault-collection-7324.html",
	"http://www.perriconemd.com/sets/perfect-pairs/concentrated-serums-7301.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/hypoallergenic-firming-eye-cream-MP0034.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/neuropeptide-eye-therapy-MP0048.html",
	"http://www.perriconemd.com/no-makeup-skincare/eyes/no-eyeshadow-eyeshadow-MP0086.html",
	"http://www.perriconemd.com/skincare/treatments/high-potency-face-firming-activator-MP0032.html",
	"http://www.perriconemd.com/supplements/healthy-weight/metabolic-support-supplements-MP0043.html",
	"http://www.perriconemd.com/no-makeup-skincare/eyes/no-mascara-mascara-MP0064.html",
	"http://www.perriconemd.com/no-makeup-skincare/eyes/no-concealer-concealer-MP0057.html",
	"http://www.perriconemd.com/no-makeup-skincare/lips/no-lipstick-lipstick-MP0063.html",
	"http://www.perriconemd.com/skincare/neck-body-firming/firming-neck-therapy-MP0024.html",
	"http://www.perriconemd.com/skincare/exfoliators-toners/intensive-pore-minimizer-MP0039.html",
	"http://www.perriconemd.com/skincare/cleansers/nutritive-cleanser-super-size-MP0093.html",
	"http://www.perriconemd.com/skincare/treatments/cold-plasma-MP0014.html",
	"http://www.perriconemd.com/skincare/shop-by-product/new/deep-crease-power-serums-90381.html",
	"http://www.perriconemd.com/skincare/shop-by-product/new/total-eye-therapy-90383.html",
	"http://www.perriconemd.com/no-makeup-skincare/lips/no-lipgloss-lipgloss-MP0062.html",
	"http://www.perriconemd.com/sets/travel-size-skincare/signature-essentials-7332.html",
	"http://www.perriconemd.com/sets/limited-edition/refirm-duo-90379.html",
	"http://www.perriconemd.com/sets/perfect-pairs/cold-plasma-face-eyes-duo-90380.html",
	"http://www.perriconemd.com/sets/perfect-pairs/eye-lift-synergy-90111.html",
	"http://www.perriconemd.com/sets/perfect-pairs/pore-power-duo-90173.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/blue-plasma-orbital-MP0010.html",
	"http://www.perriconemd.com/skincare/treatments/high-potency-amine-face-lift-MP0029.html",
	"http://www.perriconemd.com/skincare/treatments/concentrated-restorative-treatment-MP0018.html",
	"http://www.perriconemd.com/skincare/moisturizers/neuropeptide-firming-moisturizer-MP0053.html",
	"http://www.perriconemd.com/skincare/treatments/chloro-plasma-MP0012.html",
	"http://www.perriconemd.com/skincare/treatments/cold-plasma-super-size-MP0089.html",
	"http://www.perriconemd.com/skincare/moisturizers/hypoallergenic-nourishing-moisturizer-MP0036.html",
	"http://www.perriconemd.com/skincare/exfoliators-toners/serum-prep-MP0074.html",
	"http://www.perriconemd.com/supplements/healthy-weight/health-weight-management-supplements-MP0028.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-foundation-foundation-serum-MP0060.html",
	"http://www.perriconemd.com/no-makeup-skincare/the-art-of-beauty-7362.html",
	"http://www.perriconemd.com/skincare/treatments/vitamin-c-ester-15-MP0079.html",
	"http://www.perriconemd.com/skincare/neck-body-firming/cold-plasma-body-MP0015.html",
	"http://www.perriconemd.com/skincare/treatments/acyl-glutathione-deep-crease-anti-aging-serum-MP0003.html",
	"http://www.perriconemd.com/sets/limited-edition/severe-loss-of-elasticity-prescription-90160.html",
	"http://www.perriconemd.com/gift-ideas/gifts-for-you/plasma-essentials-7334.html",
	"http://www.perriconemd.com/sets/perfect-pairs/the-face-lift-duo-90113.html",
	"http://www.perriconemd.com/skincare/shop-by-product/new/day-to-night-complexion-correction-90382.html",
	"http://www.perriconemd.com/skincare/moisturizers/anti-aging-chia-serum-MP0011.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/cold-plasma-eye-MP0016.html",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/high-potency-eye-lift-MP0031.html",
	"http://www.perriconemd.com/supplements/omega-3-supplements---90-day-MP0088.html",
	"http://www.perriconemd.com/no-makeup-skincare/face/no-foundation-foundation-no.-1-MP0059.html",
	"http://www.perriconemd.com/sets/starter-kits/the-hypoallergenic-collection-90365.html",
	"http://www.perriconemd.com/sets/limited-edition/the-dmae-collection-90181.html",
	"http://www.perriconemd.com/skincare/treatments/intensive-pore-treatment-MP0040.html",
	"http://www.perriconemd.com/skincare/cleansers/hypoallergenic-gentle-cleanser-MP0035.html",
	"http://www.perriconemd.com/supplements/healthy-weight/",
	"http://www.perriconemd.com/no-makeup-skincare/lips/",
	"http://www.perriconemd.com/gift-ideas/gifts-for-you/",
	"http://www.perriconemd.com/gift-ideas/gifts-for-her/",
	"http://www.perriconemd.com/skincare/shop-by-product/new/",
	"http://www.perriconemd.com/gift-ideas/gifts-for-him/",
	"http://www.perriconemd.com/best-skin-care-products/",
	"http://www.perriconemd.com/skincare/anti-aging-eye-treatments/",
	"http://www.perriconemd.com/skincare/shop-by-product/",
	"http://www.perriconemd.com/skincare/exfoliators-toners/",
	"http://www.perriconemd.com/skincare/neck-body-firming/",
	"http://www.perriconemd.com/skincare/shop-by-concern/",
	"http://www.perriconemd.com/skincare/deep-line-wrinkle-treatments/",
	"http://www.perriconemd.com/skincare/fine-lines-wrinkle-creams/",
	"http://www.perriconemd.com/skincare/skin-firming-treatments/",
	"http://www.perriconemd.com/skincare/extreme-loss-of-elasticity/",
	"http://www.perriconemd.com/skincare/enlarged-pores-treatments/",
	"http://www.perriconemd.com/skincare/repair-sun-damage-discoloration/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/boost/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/correct/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/repair/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/restore/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/renew/",
	"http://www.perriconemd.com/skincare/shop-by-prescription/brighten-and-protect/",
	"http://www.perriconemd.com/no-makeup-skincare/face/",
	"http://www.perriconemd.com/no-makeup-skincare/eyes/",
	"http://www.perriconemd.com/sets/travel-size-skincare/",
	"http://www.perriconemd.com/supplements/skin-health/",
	"http://www.perriconemd.com/customer-service/complimentary-services.html",
	"http://www.perriconemd.com/customer-service/replenishment-service.html",
	"http://www.perriconemd.com/customer-service/shipping-info.html",
	"http://www.perriconemd.com/customer-service/customer-care.html",
	"http://www.perriconemd.com/serious-about-beauty/perricone-beauty-2.html",
	"http://www.perriconemd.com/customer-service/contact-us.html",
	"http://www.perriconemd.com/brand/affiliate-program.html"
]
urls.forEach(function(url, index){
	setTimeout(function(){
		var date = new Date()
		http.get("http://localhost:3000/fetch?url="+url,function(res){
			if(res.statusCode == 200)
				console.log("HULK:"+url+"  ---------> "+(new Date()-date))
			else
				console.log("HULK:"+url+"  ---------> "+(new Date()-date) + "-----FAIL------")
			
		}).on('error', function(err){
			console.log("HULK:"+url+"  ---------> "+(new Date()-date) + "-----FAIL------")
		})

		http.get("http://localhost:8888/fetch?url="+url,function(res){
			if(res.statusCode)
				console.log("LUTHOR:"+url+"  ---------> "+(new Date()-date))
			else
				console.log("LUTHOR:"+url+"  ---------> "+(new Date()-date) + "-----FAIL------")	
			
		}).on('error', function(err){
			console.log("LUTHOR:"+url+"  ---------> "+(new Date()-date) + "-----FAIL------")
		})
	},index*100)
})
