module.exports = {
  "port": 3000,
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36",
  "viewPort": { "width": 1440, "height": 718 },
  "resourceTimeout":10,
  "maxRetries": 5,
  "blockedResources": [
    "google-analytics.com",
    "api.mixpanel.com",
    "fonts.googleapis.com",
    "stats.g.doubleclick.net",
    "mc.yandex.ru",
    "use.typekit.net",
    "beacon.tapfiliate.com",
    "js-agent.newrelic.com",
    "api.segment.io",
    "woopra.com",
    "\\.ttf",
    "static.olark.com",
    "static.getclicky.com",
    "fast.fonts.com",
    "youtube.com\/embed",
    "cdn.heapanalytics.com",
    "googleads.g.doubleclick.net",
    "pagead2.googlesyndication.com",
    "fullstory.com/rec",
    "navilytics.com/nls_ajax.php",
    "\\.eot",
    "log.optimizely.com/event",
    "\\.otf",
    "hn.inspectlet.com",
    "\\.css"
  ]
}